name = "pdf-agent"
type = "javascript"
account_id = "f67932e71175b3ee7c945c6bb84c5259"
workers_dev = true
main = "index.js"
compatibility_date = "2025-06-14"

# Environment variables for authentication
[vars]
RATE_LIMIT_UPLOADS_PER_HOUR = "10"
RATE_LIMIT_UPLOADS_PER_DAY = "50"
API_KEY = ""

[[r2_buckets]]
binding = "loresmith_pdfs"
bucket_name = "loresmith-pdfs"

[[kv_namespaces]]
binding = "pdf_metadata"
id = "406b4a88cb804e309079650e6b53a182"
preview_id = "e9f43588be7d43c483cfb05f774e622e"